version: '3.3'
services:
  backend:
    image: dto80/se234-lab10-backend
    ports:
      - "8082:8080"
    networks:
      - spring
  frontend:
    image: dto80/se234-lab10-client
    ports:
      - "8081:80"
    networks:
      - spring

 networks:
   spring:
    external: true